-- local now, add = MiniDeps.now, MiniDeps.add
--
-- now(function()
--   add({
--     source = "folke/lazydev.nvim",
--   })
--
--   require("lazydev").setup({
--     library = {
--       -- Load luvit types when the `vim.uv` word is found
--       { path = "${3rd}/luv/library", words = { "vim%.uv" } },
--
--       -- Ensure snacks.nvim is in your mini.deps managed path
--       { path = "snacks.nvim", words = { "Snacks" } },
--     },
--   })
-- end)
